# Generated by Django 2.2 on 2020-03-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.CharField(choices=[('SC', 'SOFT COVER'), ('HC', 'HARD COVER')], default='SOFT COVER', max_length=20),
        ),
    ]
