# Generated by Django 3.0.4 on 2020-03-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200315_1823'),
        ('album', '0003_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.CharField(choices=[('SOFT COVER', 'SOFT COVER'), ('HARD COVER', 'HARD COVER')], default='SOFT COVER', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='_album_photos_+', to='photo.Photo'),
        ),
    ]
