# Generated by Django 3.0.4 on 2020-03-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
